version: "3.5"

services:
  rabbitmq:
    build: ./rabbitmq

    hostname: rabbitmq

    expose:
      - "5672" # Rabbitmq port

    ports:
      - "15672:15672"
      - "5672:5672"

  udp_node:
    build: ./udp_broker

    ports:
      - "4005" # UDP outgoing
      - "4006" # UDP incoming
    
    # network_mode: bridge
    hostname: udp_node

    # environment:
    #   RABBITMQ_HOST: localhost


    environment:
      RABBITMQ_HOST: rabbitmq

    restart: on-failure

    depends_on:
      - rabbitmq

    expose:
      - "5672"    

    volumes:
      - ../:/app

    command: "python3 -m modules.udp_broker -in 4006 -out 4005"

  udp_test:
    build: ./udp_broker

    environment:
      RABBITMQ_HOST: rabbitmq

    restart: on-failure

    expose:
      - "4005" # UDP outgoing
      - "4006" # UDP incoming

    volumes:
      - ../:/app

    command: "python3 -m modules.udp_test"

  flask:
    build: ./flask_server

    network_mode: bridge

    ports:
      - "80:5000" # UDP outgoing

    volumes:
      - ../:/app

    command: "python3 -m server.server"